### 查询课程信息
//如果需要参数需自己手动补全
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus":""
}

###
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus":""
}

### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201001",
  "price": 10,
  "originalPrice":100,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "wwww",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "tttt",
  "grade": "204001",
  "description": "通天塔"
}

### 查询课程
GET {{content_host}}/content/course/40
//Bearer, 使用OAuth2协议认证
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE3MTIwNzAwODMsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImFhYzI5OWIzLTQzZGItNDI0Zi04MjY4LThiMzI2OTc3OGZlYSIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.luNxGrpF5Adiv7-OP4oiPero2CQVfWkcUpX1m_0Aqn8

### 通过网关查询课程
GET {{gateway_host}}/content/course/40
//Bearer, 使用OAuth2协议认证
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiTeiAgeW4iFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIlwiLFwidXNlcm5hbWVcIjpcInQyXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTcxMjExMDUzMSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiJiMTdjZDUyNi0yZjRiLTRmMmMtYmM2ZC0zMTk0ZjkxNzVhY2YiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.OY2OhB1Nq94iiTb41WxZSnc0VszQ8dQTczh-h5ju2xg


### 查询课程计划
GET {{content_host}}/content/teachplan/117/tree-nodes

### 测试Freemarker
//要用http
GET http://localhost:63040/content/testfreemarker

